sv_timeout "60"
mp_playerid "2"
mp_autoteambalance "2"
mp_limitteams "0"
mp_startmoney "0"
mp_maxmoney "0"
sv_maxspeed "2000"
sv_skycolor_r "255"
sv_skycolor_g "255"
sv_skycolor_b "255"
sv_zmax "50000"
sv_airaccelerate "999"
mp_roundtime "1.55"
mp_chattime "0"
mp_round_infinite "begh"
sv_rehlds_movecmdrate_max_avg "40000"
sv_rehlds_movecmdrate_avg_punish "-1"
sv_rehlds_movecmdrate_max_burst "40000"
sv_rehlds_movecmdrate_burst_punish "-1"
sv_rehlds_stringcmdrate_max_avg "40000"
sv_rehlds_stringcmdrate_avg_punish "-1"
sv_rehlds_stringcmdrate_max_burst "40000"
sv_rehlds_stringcmdrate_burst_punish "-1"
sv_rehlds_attachedentities_playeranimationspeed_fix "1"
sv_rehlds_force_dlmax "1"
sv_auto_precache_sounds_in_models "1"
mp_auto_reload_weapons "1"
mp_roundrespawn_time "10"
mp_refill_bpammo_weapons "3"
mp_auto_join_team "0"
humans_join_team ""
mp_max_teamkills "0"
mp_hostage_hurtable "0"
mp_show_radioicon "0"
mp_show_scenarioicon "1"
mp_old_bomb_defused_sound "0"
mp_respawn_immunitytime "2.0"
mp_respawn_immunity_effects "1"
mp_respawn_immunity_force_unset "1"
mp_kill_filled_spawn "1"
mp_scoreboard_showhealth "-1"
mp_scoreboard_showmoney "-1"
mp_scoreboard_showdefkit "0"
mp_unduck_method "0"
mp_falldamage "0"
mp_item_staytime "120"
fps_max "1000"
sys_ticrate "1000"


; Cvars plugins
amx_hud_hide_money "1"
